export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"

export const PRODUCT_LIST="PRODUCT_LIST"

export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"


export const PRODUCT_DETAIL="PRODUCT_DETAIL"

export const SET_GET_FROM_CART="SET_GET_FROM_CART"

export const GET_CART="GET_CART"